// DepCalcs.h: interface for the CDepCalcs class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_DEPCALCS_H__E3A96FB3_12D0_4D18_8BD2_543011743A1E__INCLUDED_)
#define AFX_DEPCALCS_H__E3A96FB3_12D0_4D18_8BD2_543011743A1E__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000



class CDepCalcs  
{
public:
	CDepCalcs();
	virtual ~CDepCalcs();

	//Attributes
	BOOL m_IsNew;


};

#endif // !defined(AFX_DEPCALCS_H__E3A96FB3_12D0_4D18_8BD2_543011743A1E__INCLUDED_)
