//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MathcoDep.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_MATHCODEP_FORM              101
#define IDS_EDIT                        102
#define IDD_ASSET                       102
#define IDS_TOOL                        103
#define IDD_SCHEDULE                    103
#define IDM_MENU                        104
#define IDD_COMPANY                     104
#define IDR_MAIN_EDIT                   105
#define IDR_MAIN_TOOL                   106
#define IDR_DOC_TOOL                    107
#define IDM_DOCLIST                     108
#define IDR_MAINFRAME                   128
#define IDC_LIST1                       1000
#define IDC_BTN_ADD                     1001
#define IDC_BTN_EDIT                    1002
#define IDC_BTN_DEL                     1003
#define IDC_BTN_SCHED                   1004
#define IDC_EDIT1                       1006
#define IDC_TXT_NAME                    1006
#define IDC_TXT_GBASIS                  1007
#define IDC_TXT_TBASIS                  1008
#define IDC_G179                        1009
#define IDC_TXT_G179                    1009
#define IDC_T179                        1010
#define IDC_TXT_T179                    1010
#define IDC_EDIT6                       1011
#define IDC_TXT_GLIFE                   1011
#define IDC_EDIT7                       1012
#define IDC_TXT_GRESID                  1012
#define IDC_EDIT8                       1013
#define IDC_EDIT9                       1014
#define IDC_DATE_PURCH                  1017
#define IDC_DATE_DISP                   1018
#define IDC_CMB_TLIFE                   1018
#define IDC_CMB_GMETH                   1019
#define IDC_CMB_TMETH                   1020
#define IDC_FYE                         1022
#define IDC_SPIN1                       1023
#define IDC_TXT_MON                     1025
#define IDC_TXT_DAY                     1026
#define ID_EDIT_INFO                    32771
#define IDS_NEW                         65000
#define IDS_FILE                        65001
#define IDS_MHELP                       65002
#define IDS_SAVE                        65003
#define IDS_CUT                         65004
#define IDS_COPY                        65005
#define IDS_PASTE                       65006
#define IDS_THREE                       65007
#define IDS_FIVE                        65008
#define IDS_SEVEN                       65009
#define IDS_TEN                         65010
#define IDS_FIFTEEN                     65011
#define IDS_SL                          65012
#define IDS_DDB                         65013
#define IDS_15DB                        65014
#define IDS_SYD                         65015
#define IDS_MACRSHY                     65016
#define IDS_MACRSMQ                     65017
#define IDS_TWENTY                      65018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
